version: '2'
services:
  api:
    container_name: crud_api
    user: app
    build: .
    ports:
    - "5000:5000"
    volumes:
      - /opt/workspace/PYTHON/CRUD-Flask-Restplus:/opt/api
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env/api.env
  db:
    container_name: crud_db
    image: mysql:5.7
    env_file:
      - .env/db.env